server {
    listen 80; # NGINX слушает этот порт внутри контейнера

    location / {
        # Перенаправляем всё на твоё приложение
        # 'logs-app' — это имя контейнера в сети Docker
        proxy_pass http://logs-app:3000; 
        
        # Передаем реальные заголовки, чтобы приложение знало IP клиента
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
 